version: "3"

services:
  identity_server:
    build: ./Services/Identity
    # command: ["php", "bin/console", "server:start", "0.0.0.0"]
    command: sh -c "composer install && symfony local:server:start --port 4000"
    volumes:
      - ./Services/Identity:/app/identity
    working_dir: /app/identity
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL:postgresql://${IDENTITY_DB_USER}:${IDENTITY_DB_PASS}@identity_database/${IDENTITY_DB_NAME}?serverVersion=13&charset=utf8

  catalog_server:
    build: ./Services/Catalog
    command: ["php", "-S", "localhost:4001"]
    volumes:
      - ./Services/Catalog:/app/catalog
    ports:
      - "4001:4001"

  identity_database:
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${IDENTITY_DB_NAME}
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASS}
      POSTGRES_USER: ${IDENTITY_DB_USER}
    volumes:
      - identity-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  identity-data:
