version: "3"

services:
  identity_server:
    build: ./Services/Identity
    command: ["php", "-S", "localhost:4000"]
    volumes:
      - ./Services/Identity:/app/identity
    ports:
      - 4000:4000
